terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# ── Variables ──────────────────────────────────────────────────────────────────
variable "region" {
  description = "AWS region for all 3 nodes"
  default     = "ap-east-1"   # Hong Kong — closest to CS5296 students
}

variable "instance_type" {
  default = "t3.micro"
}

# ── Provider ───────────────────────────────────────────────────────────────────
provider "aws" {
  region = var.region
}

# ── SSH key: generated by Terraform, written to local file ────────────────────
resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "local_sensitive_file" "ssh_key" {
  content         = tls_private_key.ssh.private_key_pem
  filename        = "${path.module}/raft-key.pem"
  file_permission = "0600"
}

# ── Three nodes in the same region ────────────────────────────────────────────
module "node" {
  count  = 3
  source = "../modules/raft-node"

  node_id        = "node${count.index + 1}"
  instance_type  = var.instance_type
  ssh_public_key = tls_private_key.ssh.public_key_openssh
  key_pair_name  = "raft-quic-same"
}

# ── Outputs (consumed by deploy.sh) ───────────────────────────────────────────
output "node_ips" {
  description = "Public IPs of the 3 cluster nodes"
  value       = module.node[*].public_ip
}

output "ssh_key_file" {
  description = "Path to the generated SSH private key"
  value       = local_sensitive_file.ssh_key.filename
}

output "ssh_user" {
  value = "ec2-user"
}

output "scenario" {
  value = "same-region"
}

output "region_labels" {
  description = "Region label for each node (for report/charts)"
  value       = [var.region, var.region, var.region]
}
